# Generated by Django 4.2.1 on 2023-06-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, upload_to='Blog/', verbose_name='превью')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_public', models.BooleanField(default=True, verbose_name='публикация')),
                ('num_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='наименование')),
                ('about', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('about', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='Product/', verbose_name='превью')),
                ('price_lot', models.IntegerField(verbose_name='цена за покупку')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Продукция',
            },
        ),
    ]
